const http=require('http');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {Pool}=require('pg');
const PORT=Number(process.env.PORT||3000);
if(!process.env.DATABASE_URL) throw new Error('DATABASE_URL required');
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:false,max:5});
const seed=[
{id:'dk-639252269024186022',sportsbook:'DraftKings',game:'DET Lions @ BUF Bills',placedAt:'2026-09-17T00:28:23-07:00',wager:35,payout:525,odds:'+1400',promo:'Bet & Get',status:'OPEN',legs:['Josh Allen 2+ Passing Touchdowns','Jahmyr Gibbs 70+ Rushing Yards','Jahmyr Gibbs Anytime TD Scorer','Jared Goff 2+ Passing Touchdowns','Josh Allen Anytime TD Scorer','James Cook 78+ Rushing Yards']},
{id:'dk-639252229396516919',sportsbook:'DraftKings',game:'DET Lions @ BUF Bills',placedAt:'2026-09-16T23:22:20-07:00',wager:15,payout:195,odds:'+1200',promo:'+50% Parlay Boost',status:'OPEN',legs:['BUF Bills -4.5','Josh Allen Anytime TD Scorer','Jahmyr Gibbs 90+ Rushing + Receiving Yards','Josh Allen 220+ Passing Yards','Josh Allen 30+ Rushing Yards']},
{id:'dk-639252220974350103',sportsbook:'DraftKings',game:'DET Lions @ BUF Bills',placedAt:'2026-09-16T23:08:17-07:00',wager:10,payout:110,odds:'+1100',promo:'$10 Bonus Bet',bonusBet:true,status:'OPEN',legs:['BUF Bills Moneyline','D.J. Moore 5+ Receptions','Jahmyr Gibbs 70+ Rushing Yards','Josh Allen 250+ Passing Yards','James Cook Anytime TD Scorer','Jahmyr Gibbs Anytime TD Scorer']}
];
function norm(s){return String(s||'').trim().replace(/\s+/g,' ')}
function fp(b){return crypto.createHash('sha256').update([b.sportsbook,b.game,b.placedAt,b.wager,b.payout,(b.legs||[]).join('|')].map(norm).join('~').toLowerCase()).digest('hex').slice(0,24)}
function valid(b){return b&&Number(b.wager)>=0&&Number(b.payout)>0&&Array.isArray(b.legs)&&b.legs.length>0}
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS bets(id text PRIMARY KEY,fingerprint text UNIQUE NOT NULL,sportsbook text NOT NULL,game text NOT NULL,placed_at timestamptz NOT NULL,wager numeric(12,2) NOT NULL,payout numeric(12,2) NOT NULL,odds text,promo text,bonus_bet boolean NOT NULL DEFAULT false,status text NOT NULL DEFAULT 'OPEN',legs jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now())`);for(const b of seed)await insert(b,true);}
async function insert(b,seedMode=false){const fingerprint=fp(b);const id=b.id||'bet-'+Date.now()+'-'+crypto.randomBytes(3).toString('hex');const q=`INSERT INTO bets(id,fingerprint,sportsbook,game,placed_at,wager,payout,odds,promo,bonus_bet,status,legs) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb) ${seedMode?'ON CONFLICT DO NOTHING':''} RETURNING *`;const v=[id,fingerprint,norm(b.sportsbook||'Unknown'),norm(b.game||'Unknown'),b.placedAt||new Date().toISOString(),Number(b.wager),Number(b.payout),norm(b.odds),norm(b.promo),!!b.bonusBet,norm(b.status||'OPEN'),JSON.stringify(b.legs.map(norm))];return (await pool.query(q,v)).rows[0]}
function out(r){return{id:r.id,fingerprint:r.fingerprint,sportsbook:r.sportsbook,game:r.game,placedAt:r.placed_at,wager:Number(r.wager),payout:Number(r.payout),odds:r.odds,promo:r.promo,bonusBet:r.bonus_bet,status:r.status,legs:r.legs}}
async function list(){return (await pool.query('SELECT * FROM bets ORDER BY placed_at DESC, created_at DESC')).rows.map(out)}
function json(res,code,obj){res.writeHead(code,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(obj))}
function body(req){return new Promise((ok,no)=>{let s='';req.on('data',c=>{s+=c;if(s.length>1e6)req.destroy()});req.on('end',()=>{try{ok(JSON.parse(s||'{}'))}catch(e){no(e)}});req.on('error',no)})}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://x');if(u.pathname==='/health'){await pool.query('SELECT 1');return json(res,200,{ok:true,storage:'postgres'})}if(u.pathname==='/api/bets'&&req.method==='GET')return json(res,200,{bets:await list()});if(u.pathname==='/api/bets'&&req.method==='POST'){const b=await body(req);if(!valid(b))return json(res,400,{error:'Review required: wager, payout and at least one leg are required.'});try{const row=await insert(b);return json(res,201,out(row))}catch(e){if(e.code==='23505')return json(res,409,{error:'Duplicate ticket',duplicate:true});throw e}}if(u.pathname==='/api/intake'&&req.method==='POST')return json(res,501,{error:'Screenshot vision parsing is not enabled yet. No ticket was saved.'});if(req.method==='GET'){const f=u.pathname==='/'?'index.html':u.pathname.slice(1),base=path.join(process.cwd(),'public'),p=path.resolve(base,f);if(p.startsWith(base+path.sep)&&fs.existsSync(p)){const ext=path.extname(p);res.writeHead(200,{'content-type':ext==='.css'?'text/css; charset=utf-8':ext==='.js'?'text/javascript; charset=utf-8':'text/html; charset=utf-8'});return fs.createReadStream(p).pipe(res)}}res.writeHead(404);res.end('Not found')}catch(e){console.error('request-error',e.code||e.message);json(res,500,{error:'Server error'})}});
init().then(()=>server.listen(PORT,'0.0.0.0',()=>console.log('bet-tracker-v2 postgres listening',PORT))).catch(e=>{console.error('startup-db-error',e.code||e.message);process.exit(1)});