const http=require('http');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {Pool}=require('pg');
const PORT=Number(process.env.PORT||3000);
const ESPN_EVENT='401872932';
if(!process.env.DATABASE_URL) throw new Error('DATABASE_URL required');
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:false,max:5});
const seed=[
{id:'dk-639252269024186022',sportsbook:'DraftKings',game:'DET Lions @ BUF Bills',placedAt:'2026-09-17T00:28:23-07:00',wager:35,payout:525,odds:'+1400',promo:'Bet & Get',status:'OPEN',legs:['Josh Allen 2+ Passing Touchdowns','Jahmyr Gibbs 70+ Rushing Yards','Jahmyr Gibbs Anytime TD Scorer','Jared Goff 2+ Passing Touchdowns','Josh Allen Anytime TD Scorer','James Cook 78+ Rushing Yards']},
{id:'dk-639252229396516919',sportsbook:'DraftKings',game:'DET Lions @ BUF Bills',placedAt:'2026-09-16T23:22:20-07:00',wager:15,payout:195,odds:'+1200',promo:'+50% Parlay Boost',status:'OPEN',legs:['BUF Bills -4.5','Josh Allen Anytime TD Scorer','Jahmyr Gibbs 90+ Rushing + Receiving Yards','Josh Allen 220+ Passing Yards','Josh Allen 30+ Rushing Yards']},
{id:'dk-639252220974350103',sportsbook:'DraftKings',game:'DET Lions @ BUF Bills',placedAt:'2026-09-16T23:08:17-07:00',wager:10,payout:110,odds:'+1100',promo:'$10 Bonus Bet',bonusBet:true,status:'OPEN',legs:['BUF Bills Moneyline','D.J. Moore 5+ Receptions','Jahmyr Gibbs 70+ Rushing Yards','Josh Allen 250+ Passing Yards','James Cook Anytime TD Scorer','Jahmyr Gibbs Anytime TD Scorer']}
];
function norm(s){return String(s||'').trim().replace(/\s+/g,' ')}
function fp(b){return crypto.createHash('sha256').update([b.sportsbook,b.game,b.placedAt,b.wager,b.payout,(b.legs||[]).join('|')].map(norm).join('~').toLowerCase()).digest('hex').slice(0,24)}
function valid(b){return b&&Number(b.wager)>=0&&Number(b.payout)>0&&Array.isArray(b.legs)&&b.legs.length>0}
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS bets(id text PRIMARY KEY,fingerprint text UNIQUE NOT NULL,sportsbook text NOT NULL,game text NOT NULL,placed_at timestamptz NOT NULL,wager numeric(12,2) NOT NULL,payout numeric(12,2) NOT NULL,odds text,promo text,bonus_bet boolean NOT NULL DEFAULT false,status text NOT NULL DEFAULT 'OPEN',legs jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now())`);for(const b of seed)await insert(b,true)}
async function insert(b,seedMode=false){const fingerprint=fp(b),id=b.id||'bet-'+Date.now()+'-'+crypto.randomBytes(3).toString('hex');const q=`INSERT INTO bets(id,fingerprint,sportsbook,game,placed_at,wager,payout,odds,promo,bonus_bet,status,legs) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb) ${seedMode?'ON CONFLICT DO NOTHING':''} RETURNING *`;const v=[id,fingerprint,norm(b.sportsbook||'Unknown'),norm(b.game||'Unknown'),b.placedAt||new Date().toISOString(),Number(b.wager),Number(b.payout),norm(b.odds),norm(b.promo),!!b.bonusBet,norm(b.status||'OPEN'),JSON.stringify(b.legs.map(x=>typeof x==='string'?norm(x):x))];return (await pool.query(q,v)).rows[0]}
function out(r){return{id:r.id,fingerprint:r.fingerprint,sportsbook:r.sportsbook,game:r.game,placedAt:r.placed_at,wager:Number(r.wager),payout:Number(r.payout),odds:r.odds,promo:r.promo,bonusBet:r.bonus_bet,status:r.status,legs:r.legs}}
let liveCache={at:0,data:null,error:null};
async function espnLive(){if(Date.now()-liveCache.at<10000&&liveCache.data)return liveCache.data;const url=`https://site.api.espn.com/apis/site/v2/sports/football/nfl/summary?event=${ESPN_EVENT}`;const r=await fetch(url,{headers:{'user-agent':'nfl-live-bet-tracker-v2/1.0'},signal:AbortSignal.timeout(5000)});if(!r.ok)throw Error('ESPN '+r.status);const d=await r.json(),players={},teams={};for(const p of d.boxscore?.players||[]){const team=p.team?.abbreviation||p.team?.displayName||'';for(const cat of p.statistics||[]){const keys=(cat.keys||cat.labels||[]).map(x=>String(x).toLowerCase().replace(/[^a-z0-9]/g,''));for(const a of cat.athletes||[]){const name=a.athlete?.displayName||a.athlete?.shortName;if(!name)continue;const row=players[name]||(players[name]={team});const cn=String(cat.name||cat.displayName||'stat').toLowerCase().replace(/[^a-z0-9]/g,'');(a.stats||[]).forEach((v,i)=>{const raw=String(v),n=Number(raw.replace(/[^0-9.-]/g,''));if(Number.isFinite(n)){const k=keys[i]||`stat${i}`;row[`${cn}_${k}`]=n;row[`${cn}_${i}`]=n}})}}}
const comp=d.header?.competitions?.[0];for(const c of comp?.competitors||[])teams[c.team?.abbreviation||'']={score:Number(c.score||0),homeAway:c.homeAway};const status=comp?.status?.type||{};const data={players,teams,completed:!!status.completed,state:status.state||status.name||'',detail:comp?.status?.type?.detail||comp?.status?.displayClock||'',updatedAt:new Date().toISOString()};liveCache={at:Date.now(),data,error:null};return data}
function pick(o,names){for(const n of names)if(Number.isFinite(o?.[n]))return o[n];return null}
function player(live,name){if(live.players[name])return live.players[name];const q=name.toLowerCase().replace(/[^a-z]/g,'');return Object.entries(live.players).find(([k])=>k.toLowerCase().replace(/[^a-z]/g,'')===q)?.[1]||{}}
function prop(label,current,target,live,kind='number'){if(!Number.isFinite(current))return{label,current:'DATA PENDING',target:kind==='yards'?target+' yd':target,status:'LIVE',progress:0,dataPending:true};const hit=current>=target,progress=Math.max(0,Math.min(100,Math.round(current/target*100)));return{label,current:kind==='yards'?current+' yd':current,target:kind==='yards'?target+' yd':target,status:hit?'HIT':live.completed?'LOST':'LIVE',progress}}
function enrichLeg(label,live){let m,p;
if((m=label.match(/^(.+?) (\d+)\+ Passing Touchdowns$/i))){p=player(live,m[1]);return prop(label,pick(p,['passing_passingtouchdowns','passing_td','passing_touchdowns','passing_3']),+m[2],live)}
if((m=label.match(/^(.+?) (\d+)\+ Passing Yards$/i))){p=player(live,m[1]);return prop(label,pick(p,['passing_passingyards','passing_yds','passing_yards','passing_1']),+m[2],live,'yards')}
if((m=label.match(/^(.+?) (\d+)\+ Rushing Yards$/i))){p=player(live,m[1]);return prop(label,pick(p,['rushing_rushingyards','rushing_yds','rushing_yards','rushing_1']),+m[2],live,'yards')}
if((m=label.match(/^(.+?) (\d+)\+ Rushing \+ Receiving Yards$/i))){p=player(live,m[1]);const ry=pick(p,['rushing_rushingyards','rushing_yds','rushing_yards','rushing_1']),cy=pick(p,['receiving_receivingyards','receiving_yds','receiving_yards','receiving_1']);const cur=Number.isFinite(ry)&&Number.isFinite(cy)?ry+cy:null;return prop(label,cur,+m[2],live,'yards')}
if((m=label.match(/^(.+?) (\d+)\+ Receptions$/i))){p=player(live,m[1]);return prop(label,pick(p,['receiving_receptions','receiving_rec','receiving_0']),+m[2],live)}
if((m=label.match(/^(.+?) Anytime TD Scorer$/i))){p=player(live,m[1]);const rt=pick(p,['rushing_rushingtouchdowns','rushing_td','rushing_touchdowns','rushing_3']),ct=pick(p,['receiving_receivingtouchdowns','receiving_td','receiving_touchdowns','receiving_3']);const cur=(Number.isFinite(rt)?rt:0)+(Number.isFinite(ct)?ct:0);return (Number.isFinite(rt)||Number.isFinite(ct))?prop(label,cur,1,live):prop(label,null,1,live)}
if(/^BUF Bills Moneyline$/i.test(label)){const b=live.teams.BUF?.score||0,d=live.teams.DET?.score||0,winning=b>d,final=live.completed;return{label,current:`BUF ${b} – DET ${d}`,target:'BUF win',progress:winning?100:Math.max(0,50+(b-d)*8),status:final?(winning?'HIT':'LOST'):'LIVE'}}
if(/^BUF Bills -4\.5$/i.test(label)){const b=live.teams.BUF?.score||0,d=live.teams.DET?.score||0,diff=b-d,cover=diff>=5,final=live.completed;return{label,current:`BUF ${diff>=0?'+':''}${diff}`,target:'BUF +5 margin',progress:Math.max(0,Math.min(100,Math.round(diff/5*100))),status:final?(cover?'HIT':'LOST'):'LIVE'}}
return{label,status:'LIVE',progress:0,current:'—',target:'—'}}
async function list(){const rows=(await pool.query('SELECT * FROM bets ORDER BY placed_at DESC, created_at DESC')).rows.map(out);try{const live=await espnLive();return{bets:rows.map(b=>({...b,legs:(b.legs||[]).map(x=>enrichLeg(typeof x==='string'?x:x.label,live))})),live:{provider:'ESPN',eventId:ESPN_EVENT,state:live.state,detail:live.detail,updatedAt:live.updatedAt}}}catch(e){console.error('live-stats-error',e.message);return{bets:rows,live:{provider:'ESPN',error:'Live stats temporarily unavailable'}}}}
function json(res,code,obj){res.writeHead(code,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(obj))}
function body(req){return new Promise((ok,no)=>{let s='';req.on('data',c=>{s+=c;if(s.length>1e6)req.destroy()});req.on('end',()=>{try{ok(JSON.parse(s||'{}'))}catch(e){no(e)}});req.on('error',no)})}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://x');if(u.pathname==='/health'){await pool.query('SELECT 1');return json(res,200,{ok:true,storage:'postgres',liveStats:'espn'})}if(u.pathname==='/api/bets'&&req.method==='GET')return json(res,200,await list());if(u.pathname==='/api/live'&&req.method==='GET'){try{return json(res,200,await espnLive())}catch(e){return json(res,502,{error:'Live stats unavailable'})}}if(u.pathname==='/api/bets'&&req.method==='POST'){const b=await body(req);if(!valid(b))return json(res,400,{error:'Review required: wager, payout and at least one leg are required.'});try{const row=await insert(b);return json(res,201,out(row))}catch(e){if(e.code==='23505')return json(res,409,{error:'Duplicate ticket',duplicate:true});throw e}}if(u.pathname==='/api/intake'&&req.method==='POST')return json(res,501,{error:'Screenshot vision parsing is not enabled yet. No ticket was saved.'});if(req.method==='GET'){const f=u.pathname==='/'?'index.html':u.pathname.slice(1),base=path.join(process.cwd(),'public'),p=path.resolve(base,f);if(p.startsWith(base+path.sep)&&fs.existsSync(p)){const ext=path.extname(p);res.writeHead(200,{'content-type':ext==='.css'?'text/css; charset=utf-8':ext==='.js'?'text/javascript; charset=utf-8':'text/html; charset=utf-8'});return fs.createReadStream(p).pipe(res)}}res.writeHead(404);res.end('Not found')}catch(e){console.error('request-error',e.code||e.message);json(res,500,{error:'Server error'})}});
init().then(()=>server.listen(PORT,'0.0.0.0',()=>console.log('bet-tracker-v2 postgres+live listening',PORT))).catch(e=>{console.error('startup-db-error',e.code||e.message);process.exit(1)});